### ISSUE TITLE
Why is there no login system?

### ISSUE THREAD

**Issue by mliao95** [griffinsolimini/ayto#1]
As a future user, I feel the most secure way to ensure a 1-1 relationship between user and picks is to create a two-factor authentication system.  Where does this problem rank on your list of priorities?

**Comment by griffinsolimini** [comment]
We do offer a premium tier for "locking in" picks, available to end users for 6 easy installments of $189.95, payable on the 4th and 27th of every month from September to November.

Venmo:@griffin-solimini

Much Love,
Griff
VP PR (former VP Slush)
