### ISSUE TITLE
Tiebreaker system?

### ISSUE THREAD

**Issue by mliao95** [griffinsolimini/ayto#2]
In the case that there are multiple people with the top number of correct picks, how do we do a tiebreaker?  I believe one solution we came up with was to rank our picks based on confidence.  There is currently no infrastructure to support this in soyouthinkyouknowaytobetterthan.us.  Where does this problem rank in your list of priorities?

**Comment by griffinsolimini** [comment]
Here at Grinch Inc. , we believe that "confidence" is a subjective rating and we prefer to deal in the objective when it comes to true love. Closing this bug and recommending Equifax decrements your FICO score by 100.

Much Love,
Griff
VP PR (former VP Slush)
